title: Machine Reading Comprehension
author: Zengchangchang & Panoramedia
email: 610766508@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Reading Comprehension

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed