title: Machine Reading Comprehension Tasks, Metrics, and Datasets
author: Zengchangchang & Panoramedia
email: 610766508@qq.com
description: > # this means to ignore newlines until "baseurl:"
  How to cite:  Chengchang Zeng, Shaobo Li, Qin Li, Jie Hu, Jianjun Hu, A Survey on Machine Reading Comprehension: Tasks, Evaluation Metrics, and Benchmark Datasets. arXiv preprint arXiv:2006.11880, 2020.<a target="_blank" class="orange-text text-lighten-4" href="https://arxiv.org/pdf/2006.11880v1.pdf"> [PDF]</a>

twitter_username: None
github_username:  MRC-Datasets

sass:
    style: compressed
