title: Machine Reading Comprehension
author: Zengchangchang & Panoramedia
email: 610766508@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Reading Comprehension

twitter_username: None
github_username:  MRC-Datasets

sass:
    style: compressed
